### ISSUE TITLE
Support none ASCII characters in create_assignments from csv.

### ISSUE THREAD

**Issue by hmelendez** [Esri/workforce-scripts#9] opened 2017-05-10 14:05 UTC
My Description field has none ascii characters (á,é,í,ó,ú). The arcgis_api create_assignments_from_csv python creats the assignments but the Description filed scribles the words with does none ascii characters. I've atached a sample.
[my_assignments.txt](https://github.com/Esri/workforce-scripts/files/989993/my_assignments.txt)

**Comment by apulverizer** [comment] 2017-05-10 15:27
Hi @hmelendez 

I cannot open the text file in python (defaults to UTF-8 encoding); it seems to be in a different encoding than UTF-8? Do you what encoding it is in?

I added some non-ascii characters to a UTF-8 encoded CSV file and was able to create the assignments as expected. I cannot reproduce your issue.

## My simple csv
```
xField,yField,Type,Location,Dispatcher,Description,Priority,Work Order Id,Due Date,Attachment,Worker
-118.15,33.8,1,123 Street # 765,1,Test áéíóú,4,1,4/28/2016 23:59:59,,,my_username
```

## Output on workforce app:
<img width="463" alt="screen shot 2017-05-10 at 11 23 03 am" src="https://cloud.githubusercontent.com/assets/2099642/25906617/268ec8a0-3573-11e7-8445-87ebd95b041f.png">

I'm guessing it's something to do with how your csv file is encoded, but I'm not sure. Can you post a screenshot of what you see after creation and how they are jumbled?

**Comment by MikeMillerGIS** [comment] 2017-05-10 15:31
In other scripts/apps, I load files using iso-8859-1 and it load acute characters.

**Comment by apulverizer** [comment] 2017-05-10 15:52
Thanks @MikeMillerGIS that worked.

@hmelendez I was able to import your text file of assignments by doing:

```python
 with open(csvFile, 'r', encoding='iso-8859-1') as file:
        reader = csv.DictReader(file)
        for row in reader:
            assignments_in_csv.append(row)
```

Then in workforce they seem correct:
<img width="600" alt="screen shot 2017-05-10 at 11 47 35 am" src="https://cloud.githubusercontent.com/assets/2099642/25907860/ac55a5fa-3576-11e7-9c96-93fbe1261500.png">

Does that look correct? It seems to match the txt file you provided. Can you try using `iso-8859-1` encoding? See [here](https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Coverage) for language coverage.

**Comment by hmelendez** [comment] 2017-05-10 16:28
I added the enconding in line 93 but the error persists. Here is the screen capture and the csv.
![capture](https://cloud.githubusercontent.com/assets/4551911/25909678/eb326470-357b-11e7-80ed-4b13e2bfb56a.PNG)

[today_assignments.txt](https://github.com/Esri/workforce-scripts/files/990528/today_assignments.txt)

![capture2](https://cloud.githubusercontent.com/assets/4551911/25909722/11d82862-357c-11e7-9503-6d3aed740747.PNG)

**Comment by apulverizer** [comment] 2017-05-11 13:34
@hmelendez 

Okay so I looked into this a bit more. 

The first file you provided appears to be encoded as ANSI (at least that's what notepad++ sniffed from it) so you should probably use `iso-8859-1` as the encoding. This will read the the CSV you provided properly and render properly as shown in my first comment.

The second file you provided appears to be encoded as UTF-8 (at least that's what notepad++ sniffed from it) so you should use `UTF-8` as the encoding (which is default file io in python). When I do this it reads it as expected and renders accordingly:

### Reading today_assignments.txt with UTF-8 encoding
<img width="597" alt="screen shot 2017-05-11 at 9 30 08 am" src="https://cloud.githubusercontent.com/assets/2099642/25951695/7499d792-362c-11e7-8f38-2324e43e7282.png">

As far as I know there's no reliable way to determine the encoding of the file though there as some heuristics that can be used. [Chardet](https://github.com/chardet/chardet) is a library that can detect the encoding using such heuristics. You could try incorporating this library if you have to routinely read CSV files with different encodings. You could also look into how the CSV files are generated and ensure they are the same encoding.

**Comment by jonathangroves** [comment] 2017-06-10 09:23
Hi.

I'm using export_assignments_to_csv and suddenly started getting the below - any advice appreciated.

I can't find the character reported anywhere in my Assignments (was expecting it to be in Notes left by Workers but, alas not).

Thanks in advance!

Jonathan

[2017-06-10 09:14:48,319] [  export_assignments_to_csv.py: 115 -                           main()]         [MainThread] [      root] [    INFO] Authenticating...
[2017-06-10 09:14:48,807] [  export_assignments_to_csv.py: 118 -                           main()]         [MainThread] [      root] [    INFO] Getting assignment
 feature layer...
[2017-06-10 09:14:49,403] [  export_assignments_to_csv.py: 121 -                           main()]         [MainThread] [      root] [    INFO] Querying assignmen
ts...
[2017-06-10 09:14:51,005] [  export_assignments_to_csv.py: 124 -                           main()]         [MainThread] [      root] [    INFO] Writing to CSV...
[2017-06-10 09:14:56,757] [  export_assignments_to_csv.py: 149 -                       <module>()]         [MainThread] [      root] [CRITICAL] Exception detected
, script exiting
[2017-06-10 09:14:56,758] [  export_assignments_to_csv.py: 150 -                       <module>()]         [MainThread] [      root] [CRITICAL] 'ascii' codec can'
t encode character u'\u013a' in position 21: ordinal not in range(128)
[2017-06-10 09:14:56,760] [  export_assignments_to_csv.py: 151 -                       <module>()]         [MainThread] [      root] [CRITICAL] Traceback (most re
cent call last): |   File "/home/pi/arcgis/export_assignments_to_csv.py", line 147, in <module> |     main(args) |   File "/home/pi/arcgis/export_assignments_to_c
sv.py", line 125, in main |     write_assignments_to_csv(args.outCSV, assignments, args.dateFormat, args.timezone) |   File "/home/pi/arcgis/export_assignments_to
_csv.py", line 110, in write_assignments_to_csv |     writer.writerows(assignment_attributes) |   File "/usr/lib/python2.7/csv.py", line 158, in writerows |     r
eturn self.writer.writerows(rows) | UnicodeEncodeError: 'ascii' codec can't encode character u'\u013a' in position 21: ordinal not in range(128) |

^bump

**Comment by apulverizer** [comment] 2018-02-14 18:42
Closing.

The scripts assume UTF-8 encoding of CSV files. If your csv files use a different encoding then you need to specify that in the script.

**Closed as completed by apulverizer** 2018-02-14 18:42 UTC
