### ISSUE TITLE
FYI using "Work Order ID" with spaces results in error.

### ISSUE THREAD

**Issue by billwie** [Esri/workforce-scripts#29] opened 2018-06-01 14:06 UTC
oops, adding details.

I'm using the Create Assignments From CSV tool and if i name my CSV field "Work Order ID" i get an error: 
[MainThread] [      root] [CRITICAL] Traceback (most recent call last): |   File "C:\Data\FaresWorkforce\workforce-scripts-master\scripts\create_assignments_from_csv.py", line 215, in <module> |     main(args) |   File "C:\Data\FaresWorkforce\workforce-scripts-master\scripts\create_assignments_from_csv.py", line 161, in main |     if args.work_order_id_field and assignment[args.work_order_id_field]: | KeyError: 'WorkOrderId' |

Changing field to "WorkOrderID" resolved this issue

**Comment by crai3162** [comment] 2018-06-01 14:14
@billwie the Workforce schema is documented here:
http://doc.arcgis.com/en/workforce/android-phone/help/workforce-schema.htm

That may help to avoid issues like this and ensure you're using the correct field names.

**Comment by apulverizer** [comment] 2018-06-01 15:12
@billwie 

If you have different field names in your CSV file, you need to set the name using a command-line option. For example for to use `Work Order ID` you need to set `-work-order-id-field
"Work Order Id"`. Can you verify you are doing that? I cannot reproduce the issue.

**Comment by apulverizer** [comment] 2018-11-27 21:29
I'm closing this since I believe it's resolved. Feel free to re-open it if you continue to run into this issue and have a reproducible case.

**Closed as completed by apulverizer** 2018-11-27 21:29 UTC
