### ISSUE TITLE
Unknown object [OBJ] causes export_assignments_to_csv.py script to fail

### ISSUE THREAD

**Issue by jfraver** [Esri/workforce-scripts#40] opened 2019-06-29 01:20 UTC
**Describe the bug**
This script fails when it reaches an unknown object [OBJ] added to notes in Workforce. The object is not visible in Workforce, so inspectors are not sure what they do to cause the insertion of the [OBJ]. An object may be generated when the inspector saves a note while Workforce is "thinking" in dictation mode. For example, "Canceled by contractor" is what the inspector says, only "Canceled by" get written out and it still says "listening...". The inspector saves the note then opens it again and dictates "contractor". The final note is "Canceled by [OBJ] Contractor", but it looks like" Canceled by Contractor" in Workforce.

**To Reproduce**
I do not know how to reproduce the issue, but I have a Workforce project with an example note with an object. You can't actually see the object [OBJ] until you export it to Word or Excel (see attached image). I could work with someone in a remote session, or here is one of the problem notes - but I'm not sure if it will work for you - the object is at the end of the paragraph:
Stormwater follow up inspection. Continued. Minor track out on the speedway and on Tyndall. Work in the right of way. Ally is closed off. There is some dirt on the sidewalk at bus stop location. I spoke with Antonio at 602-292-0989. He would like a pre-final walk-through. I requested that he call for that inspection early next week so we can provide the time necessary for that inspection.￼

This is what it looks like copied to Word from Workforce:
![Capture](https://user-images.githubusercontent.com/15874836/60377972-a3b05380-99d0-11e9-98e5-bf32852a5dc1.PNG)

**Expected behavior**
It would be helpful if the script either skipped over records with objects, or ideally, just excluded the object from the export.

**Desktop (please complete the following information):**
 - OS: iOS - unsure if this happens with Android. 
 - OS: Scheduled Task running on Windows Server 2012 R2
 - Python Version: Python 3

**Additional context**

**Comment by apulverizer** [comment] 2019-07-01 18:53
Hi @jfraver Thanks for the detailed bug report. I can look into this but will need a feature layer that can reproduce this. My hunch is that this is a bug in the ArcGIS API for Python. If you are okay with it you, you can invite my AGOL username `aaron_nitro` to your projects group, then I can have access to the layer. If not, please follow up with an email to apulver@esri.com and we can try and sort this out.

**Comment by jfraver** [comment] 2019-07-01 19:04
Hi Aaron,
 
Thanks for your response. I just invited you to the Engineering
project, which is a test project. I own the assignment with the note
that has an object - Permit#: T18CM08778.
 
https://cotgis.maps.arcgis.com/home/item.html?id=fd4aea8e3fa749408052455bd0aca465

Jessica Fraver
GIS Data Analyst
City of Tucson
Information Technology Dept
GIS Services
520-837-6072
jessica.fraver@tucsonaz.gov 

 >>> Aaron Pulver <notifications@github.com> 7/1/2019 11:53 AM >>>
Hi @jfraver
( https://github.com/jfraver)  Thanks for the detailed bug report. I
can look into this but will need a feature layer that can reproduce
this. My hunch is that this is a bug in the ArcGIS API for Python. If
you are okay with it you, you can invite my AGOL username aaron_nitro to
your projects group, then I can have access to the layer. If not, please
follow up with an email to apulver@esri.com and we can try and sort this
out.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
(
https://github.com/Esri/workforce-scripts/issues/40?email_source=notifications&email_token=ADZDWFC6XAIVKPBPWSE6LCDP5JHBRA5CNFSM4H4JKCRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY7AX2Q#issuecomment-507382762)
, or mute the thread
(

**Comment by apulverizer** [comment] 2019-07-02 18:31
Resolved offline by explicitly setting the encoding to `utf-8` when opening the file for writing. This is because the default encoding depends on the underlying system. Closing.

**Closed as completed by apulverizer** 2019-07-02 18:31 UTC
