### ISSUE TITLE
Export to CSV file

### ISSUE THREAD

**Issue by ming800** [Esri/workforce-scripts#3] opened 2016-12-01 21:51 UTC
Because I am very new to Python and do not want to mess up the AGOL data, I am just trying to export the online assignments to CSV file. However, I got a error message as the following:
========================================================
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "C:\GIS\workforce-scripts-master\standalone_scripts\export_assignments_to_csv.py", line 31, in <module>
    import workforcehelpers
  File "C:\GIS\workforce-scripts-master\standalone_scripts\workforcehelpers.py", line 28, in <module>
    import requests
ImportError: No module named requests
>>> 
=============================================================

Here is the command line:
C:\Python27\ArcGISx6410.4\python.exe export_assignments_to_csv.py -outCSV " 
../exported_assignments.csv" -u mingzhang -p mingzhang -url "https://b-w.maps.arcgis.com" -pid "4b34bbfec3204f80b8752894f7dae8d1" -logFile "../log.txt" -outSR 102323 -where "1=1" -dateFormat "%m/%d/%Y"

Please help and let me what I did wrong!

Thank you very much,

Ming

**Comment by apulverizer** [comment] 2016-12-02 03:31
Hi Ming,

It seems like you're doing everything correctly. The error message indicates that you are missing a 3rd Party library called requests. 

Requests is [bundled](https://github.com/Esri/workforce-scripts/tree/master/requests) with this repo so it shouldn't be an issue. I'm not sure why it's not finding it. I was able to reproduce your issue, I'll look into it. 

Anyway, to immediately resolve your issue. You can do one of 2 things. 

1. Download and install requests from [here](https://pypi.python.org/pypi/requests#downloads) or you can run (from the C:\Python27\ArcGIS10.4\Scripts directory) the following command in command prompt:

```bash
pip install requests
``` 

2. Set the PYTHONPATH environment variable to include the workforce-scripts repo before executing the script. It would look something like this:

```bash
export set PYTHONPATH=%PYTHONPATH%;C:\GIS\workforce-scripts-master
```

Then if you run the script, it should work.

**Comment by apulverizer** [comment] 2017-02-22 15:22
Closing this as we have added a requirements.txt file.

You can now use `pip` to install the dependencies since they are hosted on [PyPi](https://pypi.python.org/pypi). 

If you are using Windows with ArcMap installed, the `pip` executable is generally located in `C:\Python27\ArcGIS10.X\Scripts\`. So you many need to run `C:\Python27\ArcGIS10.X\Scripts\pip.exe install -r requirements.txt` if you have not added the `Scripts` folder to your `PATH` environment variable.

**Closed as completed by apulverizer** 2017-02-22 15:22 UTC
